### PR TITLE
push notification for messagin

### PR DESCRIPTION
**Pull request by diego04**
This is the final addition for push notification for messages. It was not working yesterday because the tables were taking forever to add the columns; it is ok now.

### CODE REVIEW

**Comment by gcoomber** [comment]
Maybe I don't understand push notifications, but will this only send push notifications if the Negotiations view controller is open?

**Comment by diego04** [comment]
This will send push notification to the receiver when the sender hits the send message button. So, the sender needs his negotiation view controller open. But, the receiver of the message can have the app closed and the device locked; the receiver will still see some the message in the screen. Is that answer?

**Comment by derekdowling** [comment]
Okay, so what does the push notification look like? Will it open the user to the right negotiation or anything like that?

**Comment by diego04** [comment]
I've been trying it out, when the user unlocks the device using the push notification, they get directed to the previous screen where the app was previously open.

**Comment by derekdowling** [comment]
Closed as this was integrated in #89

**Pull request closed without merging**
