### PR TITLE
Login buttons for google and twitter.

### PR DESCRIPTION
**Pull request by hpabst**

### CODE REVIEW

**Comment by hpabst** [comment]
This is just the UI elements on the login page so that the presentation video can be made. The buttons do nothing for now.

**Comment by derekdowling** [comment]
Merge conflict :/

**Comment by hpabst** [comment]
Yep. I'm guessing it's because Xcode reordered a few segue references. GG. Looks good to do the merge otherwise?

**Comment by gcoomber** [comment]
Yeah, i'd say safe to merge. It looks like youre just touching the login screen so there shouldn't be an overlap with Derek's PR

**Comment by hpabst** [comment]
Due to problems with merging, the changes were just pushed in master.

**Pull request closed without merging**
