### PR TITLE
Ipad ui

### PR DESCRIPTION
**Pull request by hpabst**
Major changes to constraints in all screens in order for the UI to be functional on iPad.

### CODE REVIEW

**Comment by hpabst** [comment]
Note, this pull request will require a complete overwrite of the storyboard in master branch.

**Comment by gcoomber** [comment]
Once, this is merged we should test in master to double check if everything is working okay.

**Comment by derekdowling** [comment]
@hpabst and @gcoomber what's the deal here? Can we force push this.

**Comment by hpabst** [comment]
This branch has already been merged.

**Comment by derekdowling** [comment]
@hpabst you need to push your local master if that's how you did it, because github's master doesn't have that yet. Either that or someone overwrote it.

**Pull request closed without merging**
