### PR TITLE
Created Book/Listing models and Conversation model stub.

### PR DESCRIPTION
**Pull request by Torboto**

### CODE REVIEW

**Comment by hpabst** [comment]
I'm guessing that adding these models into the Parse backend is the responsibility of whoever is working on the controllers for these models?

Does the editionInfo member in Book contain both the numbered edition (e.g. 3rd edition) and the publishing date? It might be useful to separate those into 2 different members.

We probably want to have the authour(s) attached to the Book model.

We should have a member variable for the image attached to a listing in ListingModel as well. Make it nillable to indicate that the listing doesn't have an image attached?

**Comment by Torboto** [comment]
Controllers would be part of the next subtask of tying the backend/frontend together (See: https://trello.com/c/5TlqK0DU/38-listings-connect-listing-creation-to-backend). This PR maps to the cards https://trello.com/c/rijnDzBS/35-listings-book-model and https://trello.com/c/3xVluYiK/36-listings-listing-model. It is a small PR so that Kevin can get an idea for what needs to put onto the front end.

All the book properties are taken more or less from the ISBNDB data since we should be getting almost all our data from them once the ISBN stuff is implemented. In an ideal world we would be taking very little manually inputted Listings.
Their examples were:
"edition_info" : "Hardcover; 2001-10-29"
"edition_info" : "(alk. paper)"
Since they are not consistent it would be hard to break them up into smaller pieces, so I figured we might as well use their format.

Good point on the Authors and images. Will add.

**Comment by Torboto** [comment]
Since images are much later in the sprints I think it should be put off until we know exactly how they work and what actually needs to go into the model. I'm unsure if we'll need to make a model for images, and I don't know how to save/load them to Parse. I'd rather wait than do something half-baked now.

**Comment by Torboto** [comment]
Actually I lied. The model should be where all the parse stuff happens. I'll rework the models to be subclasses PFObjects so that all the logic for the models stays in the models.

**Comment by Torboto** [comment]
I have updated the models to be PFObjects, as suggested by Parse. This means we rely on the parse methods to do everything, but we can call them from our model object.

ie. var book = Book()
     book.isbn13 = "978282828282"
     book.save()

This PR is now ready to be reviewed, again.

**Comment by gcoomber** [comment]
Looks good to me. Merge away.

**Pull request merged**
